SandboxVars = {
    VERSION = 5,
    -- Changer ceci active l'option avancée \Multiplicateur de Population\. Par défaut=Normal
    -- 1 = Hardcore
    -- 2 = Très Élevé
    -- 3 = Élevé
    -- 4 = Normal
    -- 5 = Faible
    Zombies = 4,
    -- Par défaut=Focalisés en ville
    -- 1 = Focalisés en ville
    Distribution = 1,
    -- Par défaut=1 heure
    -- 1 = 15 minutes
    -- 2 = 30 minutes
    -- 3 = 1 heure
    -- 4 = 2 heures
    -- 5 = 3 heures
    -- 6 = 4 heures
    -- 7 = 5 heures
    -- 8 = 12 heures
    -- 9 = Temps réel
    -- 10 = 8 heures
    -- 11 = 9 heures
    -- 12 = 10 heures
    -- 13 = 11 heures
    -- 14 = 12 heures
    -- 15 = 13 heures
    -- 16 = 14 heures
    -- 17 = 15 heures
    -- 18 = 16 heures
    -- 19 = 17 heures
    -- 20 = 18 heures
    -- 21 = 19 heures
    -- 22 = 20 heures
    -- 23 = 21 heures
    -- 24 = 22 heures
    -- 25 = 23 heures
    DayLength = 3,
    StartYear = 1,
    -- Par défaut=Juillet
    -- 1 = Janvier
    -- 2 = Février
    -- 3 = Mars
    -- 4 = Avril
    -- 5 = Mai
    -- 6 = Juin
    -- 7 = Juillet
    -- 8 = Août
    -- 9 = Septembre
    -- 10 = Octobre
    -- 11 = Novembre
    StartMonth = 7,
    StartDay = 9,
    -- Par défaut=9 heures
    -- 1 = 7 heures
    -- 2 = 9 heures
    -- 3 = Midi
    -- 4 = 14 heures
    -- 5 = 17 heures
    -- 6 = 21 heures
    -- 7 = Minuit
    -- 8 = 2 heures
    StartTime = 2,
    -- Par défaut=0-30 jours
    -- 1 = Immédiate
    -- 2 = 0-30 jours
    -- 3 = 0-2 mois
    -- 4 = 0-6 mois
    -- 5 = 0-1 année
    -- 6 = 0-5 années
    -- 7 = 2-6 mois
    WaterShut = 2,
    -- Par défaut=0-30 jours
    -- 1 = Immédiate
    -- 2 = 0-30 jours
    -- 3 = 0-2 mois
    -- 4 = 0-6 mois
    -- 5 = 0-1 année
    -- 6 = 0-5 années
    -- 7 = 2-6 mois
    ElecShut = 2,
    -- Minimum=-1 Maximum=2147483647 Par défaut=14
    WaterShutModifier = 14,
    -- Minimum=-1 Maximum=2147483647 Par défaut=14
    ElecShutModifier = 14,
    -- Par défaut=Rare
    -- 1 = None (not recommended)
    -- 2 = Insanely Rare
    -- 3 = Extrêmement rare
    -- 4 = Rare
    -- 5 = Normal
    -- 6 = Commun
    FoodLoot = 4,
    -- Par défaut=Rare
    -- 1 = None (not recommended)
    -- 2 = Insanely Rare
    -- 3 = Extrêmement rare
    -- 4 = Rare
    -- 5 = Normal
    -- 6 = Commun
    CannedFoodLoot = 4,
    -- Par défaut=Rare
    -- 1 = None (not recommended)
    -- 2 = Insanely Rare
    -- 3 = Extrêmement rare
    -- 4 = Rare
    -- 5 = Normal
    -- 6 = Commun
    LiteratureLoot = 4,
    -- Des graines, une scie, des clous, une canne à pêche, divers outils, etc. Par défaut=Rare
    -- 1 = None (not recommended)
    -- 2 = Insanely Rare
    -- 3 = Extrêmement rare
    -- 4 = Rare
    -- 5 = Normal
    -- 6 = Commun
    SurvivalGearsLoot = 4,
    -- Par défaut=Rare
    -- 1 = None (not recommended)
    -- 2 = Insanely Rare
    -- 3 = Extrêmement rare
    -- 4 = Rare
    -- 5 = Normal
    -- 6 = Commun
    MedicalLoot = 4,
    -- Par défaut=Rare
    -- 1 = None (not recommended)
    -- 2 = Insanely Rare
    -- 3 = Extrêmement rare
    -- 4 = Rare
    -- 5 = Normal
    -- 6 = Commun
    WeaponLoot = 4,
    -- Par défaut=Rare
    -- 1 = None (not recommended)
    -- 2 = Insanely Rare
    -- 3 = Extrêmement rare
    -- 4 = Rare
    -- 5 = Normal
    -- 6 = Commun
    RangedWeaponLoot = 4,
    -- Par défaut=Rare
    -- 1 = None (not recommended)
    -- 2 = Insanely Rare
    -- 3 = Extrêmement rare
    -- 4 = Rare
    -- 5 = Normal
    -- 6 = Commun
    AmmoLoot = 4,
    -- Par défaut=Rare
    -- 1 = None (not recommended)
    -- 2 = Insanely Rare
    -- 3 = Extrêmement rare
    -- 4 = Rare
    -- 5 = Normal
    -- 6 = Commun
    MechanicsLoot = 4,
    -- Everything else. Also affects foraging for all items in Town/Road zones. Par défaut=Rare
    -- 1 = None (not recommended)
    -- 2 = Insanely Rare
    -- 3 = Extrêmement rare
    -- 4 = Rare
    -- 5 = Normal
    -- 6 = Commun
    OtherLoot = 4,
    -- Contrôle la température globale. Par défaut=Normal
    -- 1 = Très froid
    -- 2 = Froid
    -- 3 = Normal
    -- 4 = Chaud
    Temperature = 3,
    -- Contrôle la fréquence de la pluie. Par défaut=Normale
    -- 1 = Très rare
    -- 2 = Rare
    -- 3 = Normale
    -- 4 = Fréquente
    Rain = 3,
    -- Nombre de jours avant que la détérioration ne soit totale. Par défaut=Normale (100 jours)
    -- 1 = Très rapide (20 jours)
    -- 2 = Rapide (50 jours)
    -- 3 = Normale (100 jours)
    -- 4 = Lente (200 jours)
    ErosionSpeed = 3,
    -- Nombre de jours avant que la détérioration du monde soit à 100%.  -1 ne signifie pas de détérioration.  Zéro signifie qu'il faut utiliser l'option 'Vitesse de détérioration'.  Maximum 36,500 (100 ans). Minimum=-1 Maximum=36500 Par défaut=0
    ErosionDays = 0,
    -- Modifie le gain d'XP de base par actions via ce nombre. Minimum=0,00 Maximum=1000,00 Par défaut=1,00
    XpMultiplier = 1.0,
    -- Determines if the XP multiplier affects passively levelled skills eg. Fitness and Strength.
    XpMultiplierAffectsPassive = false,
    -- À utiliser pour multiplier ou réduire le volume général des moteurs Minimum=0,00 Maximum=100,00 Par défaut=1,00
    ZombieAttractionMultiplier = 1.0,
    -- Détermine si les voitures sont verrouillées, si elles ont besoin de clés pour démarrer, etc.
    VehicleEasyUse = false,
    -- Contrôle la vitesse de croissance des plantations. Par défaut=Normale
    -- 1 = Très rapide
    -- 2 = Rapide
    -- 3 = Normale
    -- 4 = Lente
    Farming = 3,
    -- Contrôle le temps qu'il faut pour que la nourriture se décompose dans un composteur. Par défaut=2 semaines
    -- 1 = 1 semaine
    -- 2 = 2 semaines
    -- 3 = 3 semaines
    -- 4 = 4 semaines
    -- 5 = 6 semaines
    -- 6 = 8 semaines
    -- 7 = 10 semaines
    CompostTime = 2,
    -- Vitesse à laquelle la faim, la soif et la fatigue du personnage diminueront. Par défaut=Normale
    -- 1 = Très rapide
    -- 2 = Rapide
    -- 3 = Normale
    -- 4 = Lente
    StatsDecrease = 3,
    -- Contrôle l'abondance des poissons et de la recherche globale. Par défaut=Normale
    -- 1 = Très pauvre
    -- 2 = Pauvre
    -- 3 = Normale
    -- 4 = Abondante
    NatureAbundance = 3,
    -- Par défaut=Parfois
    -- 1 = Jamais
    -- 2 = Très rare
    -- 3 = Rare
    -- 4 = Parfois
    -- 5 = Souvent
    Alarm = 4,
    -- À quelle fréquence les maisons et les bâtiments seront découverts verrouillés. Par défaut=Très souvent
    -- 1 = Jamais
    -- 2 = Très rare
    -- 3 = Rare
    -- 4 = Parfois
    -- 5 = Souvent
    LockedHouses = 6,
    -- Si activé, le joueur commencera avec des chips, une bouteille d'eau, un sac à dos, une batte de baseball et un marteau.
    StarterKit = false,
    -- Cochez-le pour utiliser le système de nutrition avancée (gestion des calories, du poids...)
    Nutrition = true,
    -- Définit à quelle vitesse la nourriture va périmer. Par défaut=Normale
    -- 1 = Très rapide
    -- 2 = Rapide
    -- 3 = Normale
    -- 4 = Lente
    FoodRotSpeed = 3,
    -- Définit à quel point le réfrigérateur sera efficace. Par défaut=Normale
    -- 1 = Très peu efficace
    -- 2 = Peu efficace
    -- 3 = Normale
    -- 4 = Efficace
    FridgeFactor = 3,
    -- Définit le temps durant lequel une zone ne doit pas être visitée pour provoquer la réapparition de butin. Par défaut=Jamais
    -- 1 = Jamais
    -- 2 = Tous les jours
    -- 3 = Toutes les semaines
    -- 4 = Tous les mois
    LootRespawn = 1,
    -- Quand > 0, le butin ne réapparaîtra pas dans les zones qui ont été visitées durant ce nombre d'heures en jeu. Minimum=0 Maximum=2147483647 Par défaut=0
    SeenHoursPreventLootRespawn = 0,
    -- Une liste de types d'objets séparés par des virgules, qui seront supprimés après HoursForWorldItemRemoval
    WorldItemRemovalList = "Base.Hat,Base.Glasses,Base.Maggots",
    -- Nombres d'heures écoulées depuis qu'un objet ait été jeté au sol avant d'être retiré. Les éléments au sol seront supprimés lors du prochain chargement de cette partie de la carte. Zéro signifie que les éléments ne seront pas supprimés. Minimum=0,00 Maximum=2147483647,00 Par défaut=24,00
    HoursForWorldItemRemoval = 24.0,
    -- Si activé, tous les objets qui ne sont pas dans la liste des objets retirés seront supprimés.
    ItemRemovalListBlacklistToggle = false,
    -- Ceci affectera la détérioration du monde et la péremption des aliments au lancement du serveur. Par défaut=0
    -- 1 = 0
    -- 2 = 1
    -- 3 = 2
    -- 4 = 3
    -- 5 = 4
    -- 6 = 5
    -- 7 = 6
    -- 8 = 7
    -- 9 = 8
    -- 10 = 9
    -- 11 = 10
    -- 12 = 11
    TimeSinceApo = 1,
    -- Influencera la quantité d'eau quotidienne que les plantes perdront et leur capacité à éviter les maladies. Par défaut=Normale
    -- 1 = Très forte
    -- 2 = Forte
    -- 3 = Normale
    -- 4 = Basse
    PlantResilience = 3,
    -- Contrôle le rendement des plantations lors de la récolte. Par défaut=Normale
    -- 1 = Très pauvre
    -- 2 = Pauvre
    -- 3 = Normale
    -- 4 = Abondante
    PlantAbundance = 3,
    -- Récupération de la fatigue après avoir effectué des actions. Par défaut=Normale
    -- 1 = Très rapide
    -- 2 = Rapide
    -- 3 = Normale
    -- 4 = Lente
    EndRegen = 3,
    -- Fréquence de passage des hélicoptères au-dessus de la zone de l'Évènement. Par défaut=Une fois
    -- 1 = Jamais
    -- 2 = Une fois
    -- 3 = De temps en temps
    Helicopter = 2,
    -- Fréquence des meta-évènements (coups de feu, cris, aboiements...) attirant les zombies. Par défaut=De temps en temps
    -- 1 = Jamais
    -- 2 = De temps en temps
    MetaEvent = 2,
    -- Contrôle les méta-évènements nocturnes durant le sommeil du joueur. Par défaut=Jamais
    -- 1 = Jamais
    -- 2 = De temps en temps
    SleepingEvent = 1,
    -- Augmente / réduit les chances d'apparition des groupes électrogènes sur la carte. Par défaut=Parfois
    -- 1 = Très rare
    -- 2 = Rare
    -- 3 = Parfois
    -- 4 = Souvent
    GeneratorSpawning = 3,
    -- Combien de carburant est consommé par heure en jeu. Minimum=0,00 Maximum=100,00 Par défaut=1,00
    GeneratorFuelConsumption = 1.0,
    -- Augmente / réduit la probabilité de découvrir des maisons d'anciens survivants, générées aléatoirement sur la carte, qu'elles soient brûlées, remplies de réserves, de cadavres, de survivants, etc. Par défaut=Rare
    -- 1 = Jamais
    -- 2 = Très rare
    -- 3 = Rare
    -- 4 = Parfois
    -- 5 = Souvent
    SurvivorHouseChance = 3,
    -- Par défaut=Rare
    -- 1 = Jamais
    -- 2 = Très rare
    -- 3 = Rare
    -- 4 = Parfois
    -- 5 = Souvent
    VehicleStoryChance = 3,
    -- Par défaut=Rare
    -- 1 = Jamais
    -- 2 = Très rare
    -- 3 = Rare
    -- 4 = Parfois
    -- 5 = Souvent
    ZoneStoryChance = 3,
    -- Impacte les chances de trouver une carte annotée sur un survivant décédé. Par défaut=Parfois
    -- 1 = Jamais
    -- 2 = Très rare
    -- 3 = Rare
    -- 4 = Parfois
    -- 5 = Souvent
    AnnotatedMapChance = 4,
    -- Ajoute des points gratuits durant la création du personnage. Minimum=-100 Maximum=100 Par défaut=0
    CharacterFreePoints = 0,
    -- Donne des points de vie bonus aux constructions des joueurs afin de les rendre plus résistantes aux zombies. Par défaut=Normale
    -- 1 = Très basse
    -- 2 = Basse
    -- 3 = Normale
    -- 4 = Haute
    ConstructionBonusPoints = 3,
    -- Détermine l'éclairage global la nuit. Par défaut=Normale
    -- 1 = Nuit noire
    -- 2 = Sombre
    -- 3 = Normale
    NightDarkness = 3,
    -- Détermine la durée de la nuit, du crépuscule jusqu'à l'aube. Par défaut=Normale
    -- 1 = Nuit permanente
    -- 2 = Longue
    -- 3 = Normale
    -- 4 = Courte
    NightLength = 3,
    -- Augmente ou diminue l'impact des blessures sur votre corps, et leur temps de guérison. Par défaut=Normale
    -- 1 = Basse
    -- 2 = Normale
    InjurySeverity = 2,
    -- Active ou désactive les fractures des membres lorsque les survivants sont blessés par des impacts, les dégâts de zombies et les chutes.
    BoneFracture = true,
    -- Combien de temps avant que les cadavres de zombies disparaissent. Minimum=-1,00 Maximum=2147483647,00 Par défaut=216,00
    HoursForCorpseRemoval = 216.0,
    -- Détermine l'impact de la proximité de corps en décomposition sur la santé et les émotions des joueurs. Par défaut=Normal
    -- 1 = Aucun
    -- 2 = Bas
    -- 3 = Normal
    DecayingCorpseHealthImpact = 3,
    -- À quel point le sang gicle au sol et sur les murs. Par défaut=Normale
    -- 1 = Pas de sang
    -- 2 = Basse
    -- 3 = Normale
    -- 4 = Haute
    BloodLevel = 3,
    -- Détermine la rapidité à laquelle les vêtements s'usent, se salissent et se tachent de sang. Par défaut=Normale
    -- 1 = Désactivée
    -- 2 = Lente
    -- 3 = Normale
    ClothingDegradation = 3,
    FireSpread = true,
    -- Nombre de jours dans le jeu avant que la nourriture pourrie ne soit retirée de la carte. -1 signifie que la nourriture pourrie ne sera jamais retirée. Minimum=-1 Maximum=2147483647 Par défaut=-1
    DaysForRottenFoodRemoval = -1,
    -- Si activé, les groupes électrogènes fonctionneront en extérieur, ce qui permet par exemple d'alimenter les pompes à essence.
    AllowExteriorGenerator = true,
    -- Contrôle l'intensité maximale du brouillard. Par défaut=Normale
    -- 1 = Normale
    -- 2 = Modérée
    MaxFogIntensity = 1,
    -- Contrôle l'intensité maximale de la pluie. Par défaut=Normale
    -- 1 = Normale
    -- 2 = Modérée
    MaxRainFxIntensity = 1,
    -- Si désactivé, la neige ne s'accumulera pas au sol, mais restera visible sur les toits et la végétation.
    EnableSnowOnGround = true,
    -- Si activé, certaines armes de mêlée pourront frapper plusieurs zombies à la fois.
    MultiHitZombies = false,
    -- Probabilité d'être mordu par un zombie qui attaque par-derrière. Par défaut=Haute
    -- 1 = Basse
    -- 2 = Moyenne
    RearVulnerability = 3,
    -- Désactivez pour marcher sans entrave lors des attaques de mêlée.
    AttackBlockMovements = true,
    AllClothesUnlocked = false,
    -- if disabled, tainted water will not have a warning marking it as such
    EnableTaintedWaterText = true,
    -- Détermine la fréquence à laquelle vous pouvez trouver des véhicules sur la carte. Par défaut=Normal
    -- 1 = Aucun
    -- 2 = Bas
    -- 3 = Normal
    -- 4 = Haut
    CarSpawnRate = 3,
    -- Gère les chances de trouver des véhicules contenant du carburant. Par défaut=Bas
    -- 1 = Bas
    -- 2 = Normal
    ChanceHasGas = 1,
    -- Gère le niveau de carburant des véhicules que vous découvrirez. Par défaut=Bas
    -- 1 = Très bas
    -- 2 = Bas
    -- 3 = Normal
    -- 4 = Haut
    -- 5 = Très haut
    InitialGas = 2,
    -- Permet de choisir l'état des réserves d'essence dans les stations, au départ. Par défaut=Normal
    -- 1 = Vide
    -- 2 = Super Low
    -- 3 = Très basse
    -- 4 = Basse
    -- 5 = Normal
    -- 6 = Élevée
    -- 7 = Très élevée
    -- 8 = Plein
    FuelStationGas = 5,
    -- Détermine à quel point les véhicules sont gourmands en carburant. Minimum=0,00 Maximum=100,00 Par défaut=1,00
    CarGasConsumption = 1.0,
    -- Par défaut=Rare
    -- 1 = Jamais
    -- 2 = Très rare
    -- 3 = Rare
    -- 4 = Parfois
    -- 5 = Souvent
    LockedCar = 3,
    -- Détermine la condition générale des véhicules découverts sur la carte. Par défaut=Mauvais état
    -- 1 = Très mauvais état
    -- 2 = Mauvais état
    -- 3 = État correct
    -- 4 = Bon état
    CarGeneralCondition = 2,
    -- Gère les dégâts infligés aux véhicules qui ont un accident. Par défaut=Normal
    -- 1 = Très bas
    -- 2 = Bas
    -- 3 = Normal
    -- 4 = Haut
    CarDamageOnImpact = 3,
    -- Dégâts reçus par les joueurs lors d'une collision avec un véhicule. Par défaut=Aucun
    -- 1 = Aucun
    -- 2 = Bas
    -- 3 = Normaux
    -- 4 = Élevés
    DamageToPlayerFromHitByACar = 1,
    -- Active ou non les embouteillages et carambolages qui peuvent apparaître sur les routes principales de la carte.
    TrafficJam = true,
    -- Détermine à quelle fréquence les véhicules possédant une alarme seront découverts. Par défaut=Très rare
    -- 1 = Jamais
    -- 2 = Très rare
    -- 3 = Rare
    -- 4 = Parfois
    -- 5 = Souvent
    CarAlarm = 2,
    -- Active ou non les dégâts au joueur lors d'un accident.
    PlayerDamageFromCrash = true,
    -- Combien d'heures en jeu avant que l'alarme de voiture ne cesse de retentir. Minimum=0,00 Maximum=168,00 Par défaut=0,00
    SirenShutoffHours = 0.0,
    -- Permet de savoir si le joueur peut découvrir un véhicule qui a été entretenu depuis le début de l'infection. Par défaut=Peu
    -- 1 = None
    -- 2 = Peu
    -- 3 = Quelques-uns
    RecentlySurvivorVehicles = 2,
    -- Autorise l'apparition des véhicules.
    EnableVehicles = true,
    -- Governs if poisoning food is enabled. Par défaut=True
    -- 1 = True
    -- 2 = False
    EnablePoisoning = 1,
    -- Par défaut=In and around bodies
    -- 1 = In and around bodies
    -- 2 = In bodies only
    MaggotSpawn = 1,
    -- The higher the value, the longer lightbulbs last before breaking. If 0, lightbulbs will never break. Does not affect vehicle headlights. Minimum=0,00 Maximum=1000,00 Par défaut=1,00
    LightBulbLifespan = 1.0,
    Map = {
        AllowMiniMap = true,
        AllowWorldMap = true,
        MapAllKnown = true,
    },
    ZombieLore = {
        -- Contrôle le taux de déplacement des zombies. Par défaut=Traîneur rapide
        -- 1 = Sprinteur
        -- 2 = Traîneur rapide
        -- 3 = Traîneur
        Speed = 2,
        -- Contrôle les dégâts que les zombies infligent à chaque attaque. Par défaut=Normale
        -- 1 = Surhumaine
        -- 2 = Normale
        -- 3 = Faible
        Strength = 2,
        -- Contrôle la difficulté à tuer les zombies. Par défaut=Normaux
        -- 1 = Résistants
        -- 2 = Normaux
        -- 3 = Fragiles
        Toughness = 2,
        -- Contrôle comment le virus zombie se transmet. Par défaut=Sang + Salive
        -- 1 = Sang + Salive
        -- 2 = Salive uniquement
        -- 3 = Tout le monde est infecté
        Transmission = 1,
        -- Contrôle à quelle vitesse l'infection se répand. Par défaut=2-3 jours
        -- 1 = Instantanée
        -- 2 = 0-30 secondes
        -- 3 = 0-1 minutes
        -- 4 = 0-12 heures
        -- 5 = 2-3 jours
        -- 6 = 1-2 semaines
        Mortality = 5,
        -- Contrôle à quelle vitesse le cadavre se relève en tant que zombie. Par défaut=0-1 minutes
        -- 1 = Instantané
        -- 2 = 0-30 secondes
        -- 3 = 0-1 minutes
        -- 4 = 0-12 heures
        -- 5 = 2-3 jours
        Reanimate = 3,
        -- Contrôle l'intelligence des zombies. Par défaut=Déplacements basiques
        -- 1 = Se déplacer + ouvrir les portes
        -- 2 = Se déplacer
        -- 3 = Déplacements basiques
        Cognition = 3,
        -- Contrôle quels zombies peuvent ramper sous les véhicules. Par défaut=Beaucoup
        -- 1 = Rampants uniquement
        -- 2 = Quasiment aucun
        -- 3 = Quelques rares
        -- 4 = Quelques-uns
        -- 5 = Beaucoup
        -- 6 = Énormément
        CrawlUnderVehicle = 5,
        -- Contrôle à quel point les zombies se souviennent d'un joueur après l'avoir vu ou entendu. Par défaut=Normale
        -- 1 = Longue
        -- 2 = Normale
        -- 3 = Courte
        -- 4 = Aucune
        Memory = 2,
        -- Contrôle le rayon de détection visuel des zombies. Par défaut=Normale
        -- 1 = Vue aiguisée
        -- 2 = Normale
        -- 3 = Pauvre
        Sight = 2,
        -- Contrôle le rayon de détection auditif des zombies. Par défaut=Normale
        -- 1 = Précise
        -- 2 = Normale
        -- 3 = Pauvre
        Hearing = 2,
        -- Les zombies n'ayant pas entendu/vu les joueurs peuvent attaquer les portes et les constructions lorsqu'ils errent.
        ThumpNoChasing = false,
        -- Détermine si les zombies peuvent détruire ou non les constructions et défenses des joueurs.
        ThumpOnConstruction = true,
        -- Détermine si les zombies sont plutôt actifs le jour ou la nuit.  Les zombies actifs utiliseront les paramètres du réglage de la "VITESSE". Les zombies inactifs seront plus lents, et ne suivront pas beaucoup les joueurs. Par défaut=Les deux
        -- 1 = Les deux
        -- 2 = Nocturne
        ActiveOnly = 1,
        -- Permet aux zombies d'activer les alarmes de maison lorsqu'ils passent par des fenêtres ou des portes.
        TriggerHouseAlarm = false,
        -- Si activé, quand plusieurs zombies attaquent simultanément, ils peuvent vous mettre à terre pour vous dévorer. Dépends de leur force.
        ZombiesDragDown = true,
        -- Si activé, les zombies auront une chance de se jeter en avant après avoir franchi une barrière si vous êtes trop près
        ZombiesFenceLunge = true,
        -- Par défaut=Some zombies in the world will pretend to be dead
        -- 1 = Some zombies in the world will pretend to be dead
        -- 2 = Some zombies in the world, as well as some you 'kill', can pretend to be dead
        DisableFakeDead = 1,
    },
    ZombieConfig = {
        -- Identique au réglage \Nombre de zombies\ du mode Bac à Sable. 4.0 Minimum=0,00 Maximum=4,00 Par défaut=1,00
        PopulationMultiplier = 1.0,
        -- Ajuste la population désirée au début du jeu. Minimum=0,00 Maximum=4,00 Par défaut=1,00
        PopulationStartMultiplier = 1.0,
        -- Ajuste la population désirée le jour de pic. Minimum=0,00 Maximum=4,00 Par défaut=1,50
        PopulationPeakMultiplier = 1.5,
        -- Le jour où la population atteint le pic. Minimum=1 Maximum=365 Par défaut=28
        PopulationPeakDay = 28,
        -- Le nombre d'heures qui doit s'écouler avant que les zombies puissent réapparaître dans une cellule. Si zéro, la réapparition est annulée. Minimum=0,00 Maximum=8760,00 Par défaut=72,00
        RespawnHours = 72.0,
        -- Le nombre d'heures durant lequel une cellule ne doit pas être visitée avant que les zombies ne puissent y réapparaître. Minimum=0,00 Maximum=8760,00 Par défaut=16,00
        RespawnUnseenHours = 16.0,
        -- La fraction de la population désirée d'une cellule qui devrait réapparaître à chaque période de réapparition. (Cela multiplie le nombre de Z sur une même cellule à chaque réapparition) Minimum=0,00 Maximum=1,00 Par défaut=0,10
        RespawnMultiplier = 0.1,
        -- Le nombre d'heures qui doit s'écouler avant que des zombies migrent vers des parties vides d'une même cellule. Minimum=0,00 Maximum=8760,00 Par défaut=12,00
        RedistributeHours = 12.0,
        -- La distance qu'un zombie essayera de parcourir vers le dernier son qu'il a entendu. Minimum=10 Maximum=1000 Par défaut=100
        FollowSoundDistance = 100,
        -- La taille des groupes que les zombies forment lorsqu'ils ne sont pas occupés. Zéro veut dire que les zombies ne formeront pas de groupes. Les groupes ne se forment pas dans les bâtiments ou les forêts. Minimum=0 Maximum=1000 Par défaut=20
        RallyGroupSize = 20,
        -- La distance que les zombies parcourent pour former des groupes lorsqu'ils ne sont pas occupés. Minimum=5 Maximum=50 Par défaut=20
        RallyTravelDistance = 20,
        -- La distance entre les groupes de zombies. Minimum=5 Maximum=25 Par défaut=15
        RallyGroupSeparation = 15,
        -- Distance à laquelle les membres d'un groupe restent proches du chef de groupe. Minimum=1 Maximum=10 Par défaut=3
        RallyGroupRadius = 3,
    },
}
